server {
    listen 80;
    server_name 187.124.40.28 frutariamarket.com www.frutariamarket.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name 187.124.40.28 frutariamarket.com www.frutariamarket.com;

    ssl_certificate /etc/ssl/private/certs/server-cert.pem;
    ssl_certificate_key /etc/ssl/private/certs/server-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    
    ssl_client_certificate /etc/ssl/private/certs/server-cert.pem;
    ssl_verify_client on;
    ssl_verify_depth 2;
    
    root /var/www/frutaria-market;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
