server {
    listen 80;
    server_name 187.124.40.28;

    root /var/www/frutaria-market;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
