/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "okcyiazhxbkksapocovy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rY3lpYXpoeGJra3NhcG9jb3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTE0MTcsImV4cCI6MjA4OTA2NzQxN30.f9lL7RAJXgL-XpWb9iSpiK-LTa3lCJlxQJcSRNaHkOU"